import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import deviceRouter from "./device/index.js";
import adminRouter from "./admin/index.js";
import syncReadRouter from "./syncRead.js";
import syncWriteRouter from "./syncWrite.js";
import setupTablesRouter from "./setupTables.js";
import extAuthRouter from "./ext/auth.js";
import extNotificationsRouter from "./ext/notifications.js";
import extDbProxyRouter from "./ext/dbProxy.js";
import extRapportCreditRouter from "./ext/rapportCredit.js";
import extPaHistoriqueRouter from "./ext/paHistorique.js";
import extCommercialRouter from "./ext/commercial.js";
import extGiftsRouter from "./ext/gifts.js";
import extShopStatsRouter from "./ext/shopStats.js";
import extTrackRouter from "./ext/track.js";
import extSendEmailRouter from "./ext/sendEmail.js";
import extFeedbacksRouter from "./ext/feedbacks.js";
import extMonCompteRouter from "./ext/monCompte.js";
import extPricingRulesRouter from "./ext/pricingRules.js";
import extPromoRouter from "./ext/promo.js";
import extRapportJournalierRouter from "./ext/rapportJournalier.js";
import extRevokeSessionsRouter from "./ext/revokeSessions.js";
import extBonusMatrixRouter from "./ext/bonusMatrix.js";
import extCatalogueRouter from "./ext/catalogue.js";
import extCommandesRouter from "./ext/commandes.js";
import extCutoffsRouter from "./ext/cutoffs.js";
import extDemandeAccesRouter from "./ext/demandeAcces.js";
import extDemandeCompteRouter from "./ext/demandeCompte.js";
import extShopAdminAuthRouter from "./ext/shopAdminAuth.js";
import extShopAdminPasswordRouter from "./ext/shopAdminPassword.js";
import extWebIntegrationConfigRouter from "./ext/webIntegrationConfig.js";
import extSecteursRouter from "./ext/secteurs.js";
import extStorageUsageRouter from "./ext/storageUsage.js";
import extPublicStatsRouter from "./ext/publicStats.js";
import extPushRouter from "./ext/push.js";
import extCallRouter from "./ext/call.js";
import portalTrackingRouter from "./portal/tracking.js";
import portalSupplierRouter from "./portal/supplier.js";
import aiChatRouter from "./aiChat.js";
import waGroupsRouter from "./waGroups.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/device", deviceRouter);
router.use("/admin-session", adminRouter);
router.use("/admin", adminRouter);
router.use("/sync-read", syncReadRouter);
router.use("/sync-write", syncWriteRouter);
router.use("/setup-tables", setupTablesRouter);
router.use("/ext/auth", extAuthRouter);
router.use("/ext/notifications", extNotificationsRouter);
router.use("/ext/db-login", extDbProxyRouter);
router.use("/ext/rapport-credit", extRapportCreditRouter);
router.use("/ext/pa-historique", extPaHistoriqueRouter);
router.use("/ext/commercial", extCommercialRouter);
router.use("/ext/gifts", extGiftsRouter);
router.use("/ext/shop-stats", extShopStatsRouter);
router.use("/ext/track", extTrackRouter);
router.use("/ext/send-email", extSendEmailRouter);
router.use("/ext/feedbacks", extFeedbacksRouter);
router.use("/ext/mon-compte", extMonCompteRouter);
router.use("/ext/pricing-rules", extPricingRulesRouter);
router.use("/ext/promo", extPromoRouter);
router.use("/ext/rapport-journalier", extRapportJournalierRouter);
router.use("/ext/secteurs", extSecteursRouter);
router.use("/ext/storage-usage", extStorageUsageRouter);
router.use("/ext/public-stats", extPublicStatsRouter);
router.use("/ext/push", extPushRouter);
router.use("/ext/call", extCallRouter);
router.use("/ext/revoke-sessions", extRevokeSessionsRouter);
router.use("/ext/bonus-matrix", extBonusMatrixRouter);
router.use("/ext/catalogue", extCatalogueRouter);
router.use("/ext/commandes", extCommandesRouter);
router.use("/ext/cutoffs", extCutoffsRouter);
router.use("/ext/demande-acces", extDemandeAccesRouter);
router.use("/ext/demande-compte", extDemandeCompteRouter);
router.use("/ext/shop-admin-auth", extShopAdminAuthRouter);
router.use("/ext/shop-admin-password", extShopAdminPasswordRouter);
router.use("/ext/web-integration-config", extWebIntegrationConfigRouter);
router.use("/portal/tracking", portalTrackingRouter);
router.use("/portal/supplier", portalSupplierRouter);
router.use("/ai-chat", aiChatRouter);
router.use("/wa-groups", waGroupsRouter);

export default router;
