import type { Client, Article, Fournisseur, Commande, BonLivraison, PurchaseOrder, Reception, Trip, Livreur } from "./store"

const today = new Date()
const daysAgo = (n: number) => new Date(today.getTime() - n * 86400000).toISOString().slice(0, 10)

// ── Clients ──────────────────────────────────────────────────────────────────
export const SEED_CLIENTS: Client[] = [
  {
    id: "seed-cl-001",
    nom: "Épicerie Al Amal",
    secteur: "Hay Hassani",
    zone: "Casablanca Sud",
    type: "epicerie",
    taille: "50-100kg",
    typeProduits: "moyenne",
    rotation: "journalier",
    modalitePaiement: "cash",
    plafondCredit: 5000,
    creditAutorise: false,
    creditSolde: 0,
    telephone: "0661234567",
    email: "alaimal@demo.ma",
    adresse: "12 Rue Al Amal, Hay Hassani",
    gpsLat: 33.536, gpsLng: -7.655,
    createdBy: "seed",
    createdAt: daysAgo(30),
    segment: "standard",
    loyaltyPoints: 120,
    loyaltyOptIn: true,
  },
  {
    id: "seed-cl-002",
    nom: "Superette Nour",
    secteur: "Ain Chock",
    zone: "Casablanca Est",
    type: "superette",
    taille: "150-300kg",
    typeProduits: "haute_gamme",
    rotation: "4j/6",
    modalitePaiement: "credit_7",
    plafondCredit: 20000,
    creditAutorise: true,
    creditSolde: 3200,
    telephone: "0662345678",
    email: "nour.superette@demo.ma",
    adresse: "45 Bd Hassan II, Ain Chock",
    gpsLat: 33.553, gpsLng: -7.543,
    createdBy: "seed",
    createdAt: daysAgo(45),
    segment: "vip",
    loyaltyPoints: 850,
    loyaltyOptIn: true,
  },
  {
    id: "seed-cl-003",
    nom: "Marché Centrale Wholesale",
    secteur: "Derb Omar",
    zone: "Casablanca Centre",
    type: "grossiste",
    taille: "500kg+",
    typeProduits: "entree_gamme",
    rotation: "journalier",
    modalitePaiement: "virement",
    plafondCredit: 80000,
    creditAutorise: true,
    creditSolde: 15400,
    telephone: "0521123456",
    email: "centrale.wholesale@demo.ma",
    adresse: "Derb Omar, Marché de Gros",
    gpsLat: 33.591, gpsLng: -7.617,
    createdBy: "seed",
    createdAt: daysAgo(60),
    segment: "grossiste",
    loyaltyPoints: 2400,
    loyaltyOptIn: false,
  },
  {
    id: "seed-cl-004",
    nom: "Restaurant Le Patio",
    secteur: "Anfa",
    zone: "Casablanca Ouest",
    type: "restaurant",
    taille: "150-300kg",
    typeProduits: "haute_gamme",
    rotation: "3/6",
    modalitePaiement: "cheque",
    plafondCredit: 30000,
    creditAutorise: true,
    creditSolde: 7800,
    telephone: "0522987654",
    email: "contact@lepatio-demo.ma",
    adresse: "78 Bd d'Anfa, Casablanca",
    gpsLat: 33.587, gpsLng: -7.668,
    createdBy: "seed",
    createdAt: daysAgo(20),
    segment: "vip",
    loyaltyPoints: 320,
    loyaltyOptIn: true,
  },
  {
    id: "seed-cl-005",
    nom: "Épicerie Badr",
    secteur: "Sidi Moumen",
    zone: "Casablanca Est",
    type: "epicerie",
    taille: "50-100kg",
    typeProduits: "entree_gamme",
    rotation: "2/6",
    modalitePaiement: "cash",
    plafondCredit: 3000,
    creditAutorise: false,
    creditSolde: 0,
    telephone: "0663456789",
    adresse: "Cité Attacharouk, Sidi Moumen",
    gpsLat: 33.590, gpsLng: -7.490,
    createdBy: "seed",
    createdAt: daysAgo(15),
    segment: "standard",
    loyaltyPoints: 45,
    loyaltyOptIn: false,
  },
  {
    id: "seed-cl-006",
    nom: "Hôtel Mogador Essaouira",
    secteur: "Essaouira",
    zone: "Région Marrakech-Safi",
    type: "hotel",
    taille: "350-500kg",
    typeProduits: "haute_gamme",
    rotation: "4j/6",
    modalitePaiement: "virement",
    plafondCredit: 60000,
    creditAutorise: true,
    creditSolde: 22000,
    telephone: "0524476543",
    email: "approvisionnement@mogador-demo.ma",
    adresse: "Rue Laâlouj, Essaouira",
    gpsLat: 31.508, gpsLng: -9.760,
    createdBy: "seed",
    createdAt: daysAgo(90),
    segment: "vip",
    loyaltyPoints: 1850,
    loyaltyOptIn: true,
  },
]

// ── Articles ─────────────────────────────────────────────────────────────────
// 50+ articles : Légumes, Fruits, Agrumes, Herbes — avec photos Unsplash + marketplace
export const SEED_ARTICLES: Article[] = [

  // ═══════════════════════ LÉGUMES ═══════════════════════
  {
    id: "seed-art-001", nom: "Tomates Rondes", nomAr: "طماطم", famille: "Légumes",
    unite: "kg", um: "Caisse", colisageParUM: 15, colisageCaisses: 15,
    stockDisponible: 450, stockDefect: 12, stockTheorique: 450,
    shelfLifeJours: 7, alerteShelfLifeJours: 2,
    prixAchat: 3.2, pvMethode: "pourcentage", pvValeur: 35,
    photo: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=400&h=300&fit=crop&q=80",
    prixCHR: 3.84, prixMarchand: 4.00, prixParticulier: 4.32,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 4.50, marketplaceOrdre: 1,
    marketplaceDescription: "Tomates rondes fraîches du Souss, récoltées chaque matin. Idéales pour salades, sauces et tajines.",
    marketplaceTags: ["légumes", "tomates", "frais", "local"],
    actif: true, catalogueVisible: true,
    lots: [{ lotId: "LOT-" + daysAgo(2), dateReception: daysAgo(2), quantite: 300, fournisseurNom: "Ferme Souss Agri" }],
    historiquePrixAchat: [
      { date: daysAgo(7), fournisseurId: "seed-fo-001", fournisseurNom: "Ferme Souss Agri", prixAchat: 3.0, quantite: 200 },
      { date: daysAgo(2), fournisseurId: "seed-fo-001", fournisseurNom: "Ferme Souss Agri", prixAchat: 3.2, quantite: 300 },
    ],
  },
  {
    id: "seed-art-002", nom: "Pommes de Terre", nomAr: "بطاطس", famille: "Légumes",
    unite: "kg", um: "Caisse", colisageParUM: 25, colisageCaisses: 25,
    stockDisponible: 1200, stockDefect: 30, shelfLifeJours: 30, alerteShelfLifeJours: 5,
    prixAchat: 2.1, pvMethode: "pourcentage", pvValeur: 30,
    photo: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&h=300&fit=crop&q=80",
    prixCHR: 2.52, prixMarchand: 2.63, prixParticulier: 2.73,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 2.80, marketplaceOrdre: 2,
    marketplaceDescription: "Pommes de terre de Meknès, variétés Bintje et Charlotte. Parfaites pour les fritures et les gratins.",
    marketplaceTags: ["légumes", "pommes de terre", "frais"],
    actif: true, catalogueVisible: true,
    historiquePrixAchat: [
      { date: daysAgo(14), fournisseurId: "seed-fo-002", fournisseurNom: "Coopérative Meknès", prixAchat: 2.0, quantite: 800 },
      { date: daysAgo(3), fournisseurId: "seed-fo-002", fournisseurNom: "Coopérative Meknès", prixAchat: 2.1, quantite: 600 },
    ],
  },
  {
    id: "seed-art-006", nom: "Carottes", nomAr: "جزر", famille: "Légumes",
    unite: "kg", um: "Sac", colisageParUM: 20, colisageCaisses: 20,
    stockDisponible: 380, stockDefect: 10, shelfLifeJours: 21, alerteShelfLifeJours: 3,
    prixAchat: 1.8, pvMethode: "pourcentage", pvValeur: 30,
    photo: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=300&fit=crop&q=80",
    prixCHR: 2.16, prixMarchand: 2.25, prixParticulier: 2.34,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 2.40, marketplaceOrdre: 3,
    marketplaceDescription: "Carottes fraîches de Meknès, croquantes et sucrées. Riches en bêta-carotène.",
    marketplaceTags: ["légumes", "carottes", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-009", nom: "Oignons Blancs", nomAr: "بصل أبيض", famille: "Légumes",
    unite: "kg", um: "Sac", colisageParUM: 25, colisageCaisses: 25,
    stockDisponible: 600, stockDefect: 15, shelfLifeJours: 45, alerteShelfLifeJours: 7,
    prixAchat: 1.5, pvMethode: "pourcentage", pvValeur: 33,
    photo: "https://images.unsplash.com/photo-1508747703725-719777637510?w=400&h=300&fit=crop&q=80",
    prixCHR: 1.80, prixMarchand: 1.88, prixParticulier: 2.00,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 2.00, marketplaceOrdre: 4,
    marketplaceDescription: "Oignons blancs frais, incontournables de la cuisine marocaine.",
    marketplaceTags: ["légumes", "oignons", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-010", nom: "Poivrons Rouges", nomAr: "فلفل أحمر", famille: "Légumes",
    unite: "kg", um: "Caisse", colisageParUM: 10, colisageCaisses: 10,
    stockDisponible: 180, stockDefect: 8, shelfLifeJours: 14, alerteShelfLifeJours: 3,
    prixAchat: 6.0, pvMethode: "pourcentage", pvValeur: 35,
    photo: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&h=300&fit=crop&q=80",
    prixCHR: 7.20, prixMarchand: 7.50, prixParticulier: 8.10,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 8.50, marketplaceOrdre: 5,
    marketplaceDescription: "Poivrons rouges charnus du Gharb, riches en vitamine C. Parfaits pour la chermela.",
    marketplaceTags: ["légumes", "poivrons", "frais", "colorés"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-011", nom: "Poivrons Verts", nomAr: "فلفل أخضر", famille: "Légumes",
    unite: "kg", um: "Caisse", colisageParUM: 10, colisageCaisses: 10,
    stockDisponible: 220, stockDefect: 10, shelfLifeJours: 14, alerteShelfLifeJours: 3,
    prixAchat: 4.5, pvMethode: "pourcentage", pvValeur: 33,
    photo: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&h=300&fit=crop&q=80",
    prixCHR: 5.40, prixMarchand: 5.63, prixParticulier: 5.99,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 6.00, marketplaceOrdre: 6,
    marketplaceDescription: "Poivrons verts frais, idéaux pour les tajines et les salades cuites.",
    marketplaceTags: ["légumes", "poivrons", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-012", nom: "Aubergines", nomAr: "قرع أحمر", famille: "Légumes",
    unite: "kg", um: "Caisse", colisageParUM: 12, colisageCaisses: 12,
    stockDisponible: 150, stockDefect: 7, shelfLifeJours: 10, alerteShelfLifeJours: 2,
    prixAchat: 4.0, pvMethode: "pourcentage", pvValeur: 38,
    photo: "https://images.unsplash.com/photo-1659118280850-8ccf0c41e7e1?w=400&h=300&fit=crop&q=80",
    prixCHR: 4.80, prixMarchand: 5.00, prixParticulier: 5.52,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 5.50, marketplaceOrdre: 7,
    marketplaceDescription: "Aubergines violettes brillantes, tendres et parfumées. Idéales pour le zaâlouk.",
    marketplaceTags: ["légumes", "aubergines", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-013", nom: "Concombres", nomAr: "خيار", famille: "Légumes",
    unite: "kg", um: "Caisse", colisageParUM: 15, colisageCaisses: 15,
    stockDisponible: 260, stockDefect: 12, shelfLifeJours: 10, alerteShelfLifeJours: 2,
    prixAchat: 2.5, pvMethode: "pourcentage", pvValeur: 32,
    photo: "https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400&h=300&fit=crop&q=80",
    prixCHR: 3.00, prixMarchand: 3.13, prixParticulier: 3.30,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 3.50, marketplaceOrdre: 8,
    marketplaceDescription: "Concombres frais et croquants. Parfaits pour la salade marocaine traditionnelle.",
    marketplaceTags: ["légumes", "concombres", "frais", "salade"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-014", nom: "Courgettes", nomAr: "كوسة", famille: "Légumes",
    unite: "kg", um: "Caisse", colisageParUM: 15, colisageCaisses: 15,
    stockDisponible: 200, stockDefect: 8, shelfLifeJours: 10, alerteShelfLifeJours: 2,
    prixAchat: 3.0, pvMethode: "pourcentage", pvValeur: 35,
    photo: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&fit=crop&q=80",
    prixCHR: 3.60, prixMarchand: 3.75, prixParticulier: 4.05,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 4.00, marketplaceOrdre: 9,
    marketplaceDescription: "Courgettes tendres et savoureuses. Incontournables pour les tajines et les gratins.",
    marketplaceTags: ["légumes", "courgettes", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-015", nom: "Ail Frais", nomAr: "ثوم طازج", famille: "Légumes",
    unite: "kg", um: "Filet", colisageParUM: 1, colisageCaisses: 10,
    stockDisponible: 80, stockDefect: 3, shelfLifeJours: 60, alerteShelfLifeJours: 10,
    prixAchat: 12.0, pvMethode: "pourcentage", pvValeur: 38,
    photo: "https://images.unsplash.com/photo-1587049014078-3e50c0a5e42c?w=400&h=300&fit=crop&q=80",
    prixCHR: 14.40, prixMarchand: 15.00, prixParticulier: 16.56,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 18.00, marketplaceOrdre: 10,
    marketplaceDescription: "Ail frais de Meknès, très parfumé. Base indispensable de toute cuisine marocaine.",
    marketplaceTags: ["légumes", "ail", "aromatiques", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-016", nom: "Piments Forts", nomAr: "فلفل حار", famille: "Légumes",
    unite: "kg", um: "Barquette", colisageParUM: 0.5, colisageCaisses: 5,
    stockDisponible: 40, stockDefect: 2, shelfLifeJours: 14, alerteShelfLifeJours: 3,
    prixAchat: 8.0, pvMethode: "pourcentage", pvValeur: 40,
    photo: "https://images.unsplash.com/photo-1592419044706-39796d40f98c?w=400&h=300&fit=crop&q=80",
    prixCHR: 9.60, prixMarchand: 10.00, prixParticulier: 11.20,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 12.00, marketplaceOrdre: 11,
    marketplaceDescription: "Piments forts frais pour harissa maison et plats épicés.",
    marketplaceTags: ["légumes", "piments", "épicé", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-017", nom: "Haricots Verts", nomAr: "لوبيا خضرا", famille: "Légumes",
    unite: "kg", um: "Caisse", colisageParUM: 5, colisageCaisses: 5,
    stockDisponible: 120, stockDefect: 6, shelfLifeJours: 7, alerteShelfLifeJours: 2,
    prixAchat: 7.5, pvMethode: "pourcentage", pvValeur: 36,
    photo: "https://images.unsplash.com/photo-1582515073490-39981397c445?w=400&h=300&fit=crop&q=80",
    prixCHR: 9.00, prixMarchand: 9.38, prixParticulier: 10.20,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 10.50, marketplaceOrdre: 12,
    marketplaceDescription: "Haricots verts fins et croquants. Parfaits pour les salades et les tajines.",
    marketplaceTags: ["légumes", "haricots verts", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-018", nom: "Épinards Frais", nomAr: "سبانخ", famille: "Légumes",
    unite: "kg", um: "Botte", colisageParUM: 0.5, colisageCaisses: 5,
    stockDisponible: 60, stockDefect: 5, shelfLifeJours: 5, alerteShelfLifeJours: 1,
    prixAchat: 5.0, pvMethode: "pourcentage", pvValeur: 40,
    photo: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=300&fit=crop&q=80",
    prixCHR: 6.00, prixMarchand: 6.25, prixParticulier: 7.00,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 7.00, marketplaceOrdre: 13,
    marketplaceDescription: "Épinards frais en bottes, feuilles tendres et nutritives.",
    marketplaceTags: ["légumes", "épinards", "frais", "vert"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-019", nom: "Chou-fleur", nomAr: "قرنبيط", famille: "Légumes",
    unite: "pièce", um: "Pièce", colisageParUM: 1, colisageCaisses: 8,
    stockDisponible: 90, stockDefect: 5, shelfLifeJours: 10, alerteShelfLifeJours: 2,
    prixAchat: 5.0, pvMethode: "pourcentage", pvValeur: 30,
    photo: "https://images.unsplash.com/photo-1510627489930-0c1b0bfb6785?w=400&h=300&fit=crop&q=80",
    prixCHR: 6.00, prixMarchand: 6.25, prixParticulier: 6.50,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 6.50, marketplaceOrdre: 14,
    marketplaceDescription: "Chou-fleur blanc et ferme, idéal pour les gratins et les soupes.",
    marketplaceTags: ["légumes", "chou-fleur", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-020", nom: "Salade Laitue", nomAr: "خس", famille: "Légumes",
    unite: "pièce", um: "Pièce", colisageParUM: 1, colisageCaisses: 12,
    stockDisponible: 150, stockDefect: 8, shelfLifeJours: 5, alerteShelfLifeJours: 1,
    prixAchat: 2.0, pvMethode: "pourcentage", pvValeur: 38,
    photo: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop&q=80",
    prixCHR: 2.40, prixMarchand: 2.50, prixParticulier: 2.76,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 3.00, marketplaceOrdre: 15,
    marketplaceDescription: "Laitue fraîche croquante. Idéale pour les salades légères et les wraps.",
    marketplaceTags: ["légumes", "salade", "frais", "vert"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-021", nom: "Artichaut", nomAr: "قرشوف", famille: "Légumes",
    unite: "pièce", um: "Pièce", colisageParUM: 1, colisageCaisses: 6,
    stockDisponible: 70, stockDefect: 4, shelfLifeJours: 7, alerteShelfLifeJours: 2,
    prixAchat: 4.0, pvMethode: "pourcentage", pvValeur: 40,
    photo: "https://images.unsplash.com/photo-1567375698348-5d9d5ae99de0?w=400&h=300&fit=crop&q=80",
    prixCHR: 4.80, prixMarchand: 5.00, prixParticulier: 5.60,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 6.00, marketplaceOrdre: 16,
    marketplaceDescription: "Artichauts frais de saison, tendres et savoureux.",
    marketplaceTags: ["légumes", "artichaut", "frais", "saisonnier"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-022", nom: "Betteraves Rouges", nomAr: "شمندر أحمر", famille: "Légumes",
    unite: "kg", um: "Filet", colisageParUM: 1, colisageCaisses: 10,
    stockDisponible: 100, stockDefect: 4, shelfLifeJours: 21, alerteShelfLifeJours: 4,
    prixAchat: 3.0, pvMethode: "pourcentage", pvValeur: 33,
    photo: "https://images.unsplash.com/photo-1593424526416-2e9e5b0abb14?w=400&h=300&fit=crop&q=80",
    prixCHR: 3.60, prixMarchand: 3.75, prixParticulier: 3.99,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 4.00, marketplaceOrdre: 17,
    marketplaceDescription: "Betteraves rouges sucrées, crues ou cuites. Riches en antioxydants.",
    marketplaceTags: ["légumes", "betteraves", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-023", nom: "Navet Blanc", nomAr: "لفت أبيض", famille: "Légumes",
    unite: "kg", um: "Caisse", colisageParUM: 15, colisageCaisses: 15,
    stockDisponible: 120, stockDefect: 5, shelfLifeJours: 21, alerteShelfLifeJours: 4,
    prixAchat: 2.0, pvMethode: "pourcentage", pvValeur: 30,
    photo: "https://images.unsplash.com/photo-1572859099717-ed3e4bb4f0a8?w=400&h=300&fit=crop&q=80",
    prixCHR: 2.40, prixMarchand: 2.50, prixParticulier: 2.60,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 2.60, marketplaceOrdre: 18,
    marketplaceDescription: "Navets blancs frais, indispensables dans les couscous et les soupes.",
    marketplaceTags: ["légumes", "navet", "frais"],
    actif: true, catalogueVisible: true,
  },

  // ═══════════════════════ FRUITS ═══════════════════════
  {
    id: "seed-art-003", nom: "Fraises Kenitra", nomAr: "فراولة", famille: "Fruits",
    unite: "kg", um: "Barquette", colisageParUM: 0.5,
    stockDisponible: 85, stockDefect: 8, shelfLifeJours: 4, alerteShelfLifeJours: 1,
    prixAchat: 18.0, pvMethode: "pourcentage", pvValeur: 40,
    photo: "https://images.unsplash.com/photo-1601004890657-6646e1ff5e20?w=400&h=300&fit=crop&q=80",
    prixCHR: 21.60, prixMarchand: 22.50, prixParticulier: 25.20,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 28.00, marketplaceOrdre: 20,
    marketplaceDescription: "Fraises de Kenitra, sucrées et parfumées. Récoltées chaque matin de janvier à avril.",
    marketplaceTags: ["fruits", "fraises", "frais", "saisonnier", "nouveau"],
    marketplacePromo: { actif: true, prixPromo: 25.00, etiquette: "Saison Fraises !" },
    actif: true, catalogueVisible: true,
    lots: [{ lotId: "LOT-" + daysAgo(1), dateReception: daysAgo(1), quantite: 85, fournisseurNom: "Coopérative Gharb" }],
  },
  {
    id: "seed-art-005", nom: "Avocats Hass", nomAr: "أفوكادو", famille: "Fruits",
    unite: "kg", um: "Caisse", colisageParUM: 10, colisageCaisses: 10,
    stockDisponible: 120, stockDefect: 5, shelfLifeJours: 10, alerteShelfLifeJours: 3,
    prixAchat: 22.0, pvMethode: "pourcentage", pvValeur: 38,
    photo: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=300&fit=crop&q=80",
    prixCHR: 26.40, prixMarchand: 27.50, prixParticulier: 30.36,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 35.00, marketplaceOrdre: 21,
    marketplaceDescription: "Avocats Hass du Souss, crémeux et nutritifs. Riches en bonnes graisses.",
    marketplaceTags: ["fruits", "avocats", "frais", "premium"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-024", nom: "Pommes Golden", nomAr: "تفاح ذهبي", famille: "Fruits",
    unite: "kg", um: "Caisse", colisageParUM: 18, colisageCaisses: 18,
    stockDisponible: 320, stockDefect: 12, shelfLifeJours: 30, alerteShelfLifeJours: 5,
    prixAchat: 6.0, pvMethode: "pourcentage", pvValeur: 33,
    photo: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&h=300&fit=crop&q=80",
    prixCHR: 7.20, prixMarchand: 7.50, prixParticulier: 7.98,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 8.50, marketplaceOrdre: 22,
    marketplaceDescription: "Pommes Golden du Moyen Atlas, croquantes et sucrées.",
    marketplaceTags: ["fruits", "pommes", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-025", nom: "Poires Williams", nomAr: "إجاص", famille: "Fruits",
    unite: "kg", um: "Caisse", colisageParUM: 15, colisageCaisses: 15,
    stockDisponible: 140, stockDefect: 8, shelfLifeJours: 14, alerteShelfLifeJours: 3,
    prixAchat: 7.0, pvMethode: "pourcentage", pvValeur: 36,
    photo: "https://images.unsplash.com/photo-1514756331096-242fdeb70d4a?w=400&h=300&fit=crop&q=80",
    prixCHR: 8.40, prixMarchand: 8.75, prixParticulier: 9.52,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 10.00, marketplaceOrdre: 23,
    marketplaceDescription: "Poires Williams juteuses et parfumées du Maroc.",
    marketplaceTags: ["fruits", "poires", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-026", nom: "Raisins Rouges", nomAr: "عنب أحمر", famille: "Fruits",
    unite: "kg", um: "Caisse", colisageParUM: 8, colisageCaisses: 8,
    stockDisponible: 95, stockDefect: 6, shelfLifeJours: 14, alerteShelfLifeJours: 3,
    prixAchat: 10.0, pvMethode: "pourcentage", pvValeur: 40,
    photo: "https://images.unsplash.com/photo-1537640538966-cf936f9c6d67?w=400&h=300&fit=crop&q=80",
    prixCHR: 12.00, prixMarchand: 12.50, prixParticulier: 14.00,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 15.00, marketplaceOrdre: 24,
    marketplaceDescription: "Raisins rouges charnus et sucrés de la région de Meknès.",
    marketplaceTags: ["fruits", "raisins", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-027", nom: "Pastèque", nomAr: "دلاح", famille: "Fruits",
    unite: "kg", um: "Pièce", colisageParUM: 8, colisageCaisses: 4,
    stockDisponible: 200, stockDefect: 10, shelfLifeJours: 21, alerteShelfLifeJours: 4,
    prixAchat: 1.8, pvMethode: "pourcentage", pvValeur: 33,
    photo: "https://images.unsplash.com/photo-1563114773-84221bd62daa?w=400&h=300&fit=crop&q=80",
    prixCHR: 2.16, prixMarchand: 2.25, prixParticulier: 2.40,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 2.50, marketplaceOrdre: 25,
    marketplaceDescription: "Pastèques sucrées et juteuses, rafraîchissantes en été.",
    marketplaceTags: ["fruits", "pastèque", "frais", "estival"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-028", nom: "Melon Cantaloup", nomAr: "بطيخ أصفر", famille: "Fruits",
    unite: "kg", um: "Pièce", colisageParUM: 2, colisageCaisses: 6,
    stockDisponible: 80, stockDefect: 5, shelfLifeJours: 14, alerteShelfLifeJours: 3,
    prixAchat: 4.0, pvMethode: "pourcentage", pvValeur: 38,
    photo: "https://images.unsplash.com/photo-1571575173700-afb9492e6a50?w=400&h=300&fit=crop&q=80",
    prixCHR: 4.80, prixMarchand: 5.00, prixParticulier: 5.52,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 6.00, marketplaceOrdre: 26,
    marketplaceDescription: "Melon cantaloup parfumé et sucré. Idéal pour le dessert ou le petit-déjeuner.",
    marketplaceTags: ["fruits", "melon", "frais", "estival"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-029", nom: "Mangue Keitt", nomAr: "مانجو", famille: "Fruits Tropicaux",
    unite: "kg", um: "Caisse", colisageParUM: 5, colisageCaisses: 5,
    stockDisponible: 60, stockDefect: 4, shelfLifeJours: 10, alerteShelfLifeJours: 2,
    prixAchat: 14.0, pvMethode: "pourcentage", pvValeur: 43,
    photo: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=400&h=300&fit=crop&q=80",
    prixCHR: 16.80, prixMarchand: 17.50, prixParticulier: 20.00,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 22.00, marketplaceOrdre: 27,
    marketplaceDescription: "Mangues Keitt juteuses et peu fibreuses, importées fraîches.",
    marketplaceTags: ["fruits", "mangue", "tropical", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-030", nom: "Kiwi", nomAr: "كيوي", famille: "Fruits",
    unite: "kg", um: "Filet", colisageParUM: 1, colisageCaisses: 8,
    stockDisponible: 80, stockDefect: 4, shelfLifeJours: 21, alerteShelfLifeJours: 4,
    prixAchat: 12.0, pvMethode: "pourcentage", pvValeur: 40,
    photo: "https://images.unsplash.com/photo-1585059895524-72359e06133a?w=400&h=300&fit=crop&q=80",
    prixCHR: 14.40, prixMarchand: 15.00, prixParticulier: 16.80,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 18.00, marketplaceOrdre: 28,
    marketplaceDescription: "Kiwis verts juteux, riches en vitamine C.",
    marketplaceTags: ["fruits", "kiwi", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-031", nom: "Pêches", nomAr: "خوخ", famille: "Fruits",
    unite: "kg", um: "Caisse", colisageParUM: 10, colisageCaisses: 10,
    stockDisponible: 110, stockDefect: 8, shelfLifeJours: 7, alerteShelfLifeJours: 2,
    prixAchat: 8.0, pvMethode: "pourcentage", pvValeur: 38,
    photo: "https://images.unsplash.com/photo-1629828874514-17c66f7b5d3b?w=400&h=300&fit=crop&q=80",
    prixCHR: 9.60, prixMarchand: 10.00, prixParticulier: 11.04,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 12.00, marketplaceOrdre: 29,
    marketplaceDescription: "Pêches juteuses et parfumées de la région de Beni Mellal.",
    marketplaceTags: ["fruits", "pêches", "frais", "saisonnier"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-032", nom: "Figues Fraîches", nomAr: "تين طازج", famille: "Fruits",
    unite: "kg", um: "Caisse", colisageParUM: 5, colisageCaisses: 5,
    stockDisponible: 50, stockDefect: 6, shelfLifeJours: 5, alerteShelfLifeJours: 1,
    prixAchat: 15.0, pvMethode: "pourcentage", pvValeur: 40,
    photo: "https://images.unsplash.com/photo-1601648764658-cf37e8c89b70?w=400&h=300&fit=crop&q=80",
    prixCHR: 18.00, prixMarchand: 18.75, prixParticulier: 21.00,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 22.00, marketplaceOrdre: 30,
    marketplaceDescription: "Figues fraîches sucrées de Boulemane et Midelt.",
    marketplaceTags: ["fruits", "figues", "frais", "saisonnier"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-033", nom: "Grenade", nomAr: "رمان", famille: "Fruits",
    unite: "kg", um: "Caisse", colisageParUM: 10, colisageCaisses: 10,
    stockDisponible: 130, stockDefect: 6, shelfLifeJours: 30, alerteShelfLifeJours: 5,
    prixAchat: 8.0, pvMethode: "pourcentage", pvValeur: 38,
    photo: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&h=300&fit=crop&q=80",
    prixCHR: 9.60, prixMarchand: 10.00, prixParticulier: 11.04,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 12.00, marketplaceOrdre: 31,
    marketplaceDescription: "Grenades rouges juteuses et antioxydantes du Maroc.",
    marketplaceTags: ["fruits", "grenade", "frais"],
    actif: true, catalogueVisible: true,
  },

  // ═══════════════════════ AGRUMES ═══════════════════════
  {
    id: "seed-art-004", nom: "Oranges Navel", nomAr: "برتقال نافل", famille: "Agrumes",
    unite: "kg", um: "Filet 5kg", colisageParUM: 5, colisageCaisses: 20,
    stockDisponible: 680, stockDefect: 15, shelfLifeJours: 21, alerteShelfLifeJours: 4,
    prixAchat: 4.5, pvMethode: "pourcentage", pvValeur: 25,
    photo: "https://images.unsplash.com/photo-1547514701-42782101795e?w=400&h=300&fit=crop&q=80",
    prixCHR: 5.40, prixMarchand: 5.63, prixParticulier: 5.63,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 6.00, marketplaceOrdre: 35,
    marketplaceDescription: "Oranges Navel du Souss, sans pépins et très sucrées. Idéales pour les jus frais.",
    marketplaceTags: ["agrumes", "oranges", "frais", "jus"],
    actif: true, catalogueVisible: true,
    historiquePrixAchat: [
      { date: daysAgo(10), fournisseurId: "seed-fo-001", fournisseurNom: "Ferme Souss Agri", prixAchat: 4.2, quantite: 400 },
    ],
  },
  {
    id: "seed-art-007", nom: "Citrons Eureka", nomAr: "ليمون يوريكا", famille: "Agrumes",
    unite: "kg", um: "Caisse", colisageParUM: 15, colisageCaisses: 15,
    stockDisponible: 210, stockDefect: 4, shelfLifeJours: 28, alerteShelfLifeJours: 5,
    prixAchat: 5.0, pvMethode: "pourcentage", pvValeur: 28,
    photo: "https://images.unsplash.com/photo-1588165171850-4e5f119d2d78?w=400&h=300&fit=crop&q=80",
    prixCHR: 6.00, prixMarchand: 6.25, prixParticulier: 6.40,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 7.00, marketplaceOrdre: 36,
    marketplaceDescription: "Citrons Eureka juteux, indispensables pour sauces, marinades et conserves.",
    marketplaceTags: ["agrumes", "citrons", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-034", nom: "Clémentines", nomAr: "يوسفي", famille: "Agrumes",
    unite: "kg", um: "Filet 2kg", colisageParUM: 2, colisageCaisses: 15,
    stockDisponible: 450, stockDefect: 15, shelfLifeJours: 21, alerteShelfLifeJours: 4,
    prixAchat: 5.5, pvMethode: "pourcentage", pvValeur: 27,
    photo: "https://images.unsplash.com/photo-1547514701-42782101795e?w=400&h=300&fit=crop&q=80",
    prixCHR: 6.60, prixMarchand: 6.88, prixParticulier: 6.99,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 7.50, marketplaceOrdre: 37,
    marketplaceDescription: "Clémentines marocaines (Yousfi) sans pépins, faciles à éplucher.",
    marketplaceTags: ["agrumes", "clémentines", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-035", nom: "Pamplemousse", nomAr: "برتقال هندي", famille: "Agrumes",
    unite: "kg", um: "Filet", colisageParUM: 3, colisageCaisses: 10,
    stockDisponible: 90, stockDefect: 5, shelfLifeJours: 28, alerteShelfLifeJours: 5,
    prixAchat: 4.0, pvMethode: "pourcentage", pvValeur: 35,
    photo: "https://images.unsplash.com/photo-1572144883195-36b50c5a9ce5?w=400&h=300&fit=crop&q=80",
    prixCHR: 4.80, prixMarchand: 5.00, prixParticulier: 5.40,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 5.50, marketplaceOrdre: 38,
    marketplaceDescription: "Pamplemousses frais, légèrement acidulés. Idéals pour le breakfast.",
    marketplaceTags: ["agrumes", "pamplemousse", "frais"],
    actif: true, catalogueVisible: true,
  },

  // ═══════════════════════ FRUITS TROPICAUX ═══════════════════════
  {
    id: "seed-art-008", nom: "Bananes Cavendish", nomAr: "موز", famille: "Fruits Tropicaux",
    unite: "kg", um: "Régime", colisageParUM: 18,
    stockDisponible: 270, stockDefect: 20, shelfLifeJours: 7, alerteShelfLifeJours: 2,
    prixAchat: 7.5, pvMethode: "pourcentage", pvValeur: 32,
    photo: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=300&fit=crop&q=80",
    prixCHR: 9.00, prixMarchand: 9.38, prixParticulier: 9.90,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 10.00, marketplaceOrdre: 40,
    marketplaceDescription: "Bananes Cavendish fraîches importées. Énergétiques et nutritives.",
    marketplaceTags: ["fruits", "bananes", "tropical", "frais"],
    actif: true, catalogueVisible: true,
  },

  // ═══════════════════════ HERBES & AROMATIQUES ═══════════════════════
  {
    id: "seed-art-036", nom: "Coriandre Fraîche", nomAr: "قزبر", famille: "Herbes",
    unite: "botte", um: "Botte", colisageParUM: 1,
    stockDisponible: 200, stockDefect: 10, shelfLifeJours: 5, alerteShelfLifeJours: 1,
    prixAchat: 1.5, pvMethode: "pourcentage", pvValeur: 67,
    photo: "https://images.unsplash.com/photo-1600857544200-b2f468e09e53?w=400&h=300&fit=crop&q=80",
    prixCHR: 1.80, prixMarchand: 2.00, prixParticulier: 2.50,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 2.50, marketplaceOrdre: 50,
    marketplaceDescription: "Coriandre fraîche en bottes, parfum intense. Base de la cuisine marocaine.",
    marketplaceTags: ["herbes", "coriandre", "aromatiques", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-037", nom: "Persil Plat", nomAr: "معدنوس", famille: "Herbes",
    unite: "botte", um: "Botte", colisageParUM: 1,
    stockDisponible: 180, stockDefect: 8, shelfLifeJours: 5, alerteShelfLifeJours: 1,
    prixAchat: 1.0, pvMethode: "pourcentage", pvValeur: 100,
    photo: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400&h=300&fit=crop&q=80",
    prixCHR: 1.20, prixMarchand: 1.50, prixParticulier: 2.00,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 2.00, marketplaceOrdre: 51,
    marketplaceDescription: "Persil plat frais en bottes, essentiel pour les sauces et marinades.",
    marketplaceTags: ["herbes", "persil", "aromatiques", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-038", nom: "Menthe Fraîche", nomAr: "نعناع", famille: "Herbes",
    unite: "botte", um: "Botte", colisageParUM: 1,
    stockDisponible: 250, stockDefect: 12, shelfLifeJours: 5, alerteShelfLifeJours: 1,
    prixAchat: 1.0, pvMethode: "pourcentage", pvValeur: 100,
    photo: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=400&h=300&fit=crop&q=80",
    prixCHR: 1.20, prixMarchand: 1.50, prixParticulier: 2.00,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 2.00, marketplaceOrdre: 52,
    marketplaceDescription: "Menthe fraîche marocaine, parfum intense. Indispensable pour le thé à la menthe.",
    marketplaceTags: ["herbes", "menthe", "aromatiques", "frais", "thé"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-039", nom: "Basilic Frais", nomAr: "ريحان", famille: "Herbes",
    unite: "botte", um: "Pot", colisageParUM: 1,
    stockDisponible: 60, stockDefect: 4, shelfLifeJours: 5, alerteShelfLifeJours: 1,
    prixAchat: 3.0, pvMethode: "pourcentage", pvValeur: 67,
    photo: "https://images.unsplash.com/photo-1618375531912-867984bdfd87?w=400&h=300&fit=crop&q=80",
    prixCHR: 3.60, prixMarchand: 4.00, prixParticulier: 5.00,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 5.00, marketplaceOrdre: 53,
    marketplaceDescription: "Basilic frais parfumé, idéal pour les pesto et les plats italiens et orientaux.",
    marketplaceTags: ["herbes", "basilic", "aromatiques", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-040", nom: "Thym Frais", nomAr: "زعتر", famille: "Herbes",
    unite: "botte", um: "Botte", colisageParUM: 1,
    stockDisponible: 80, stockDefect: 4, shelfLifeJours: 7, alerteShelfLifeJours: 2,
    prixAchat: 3.5, pvMethode: "pourcentage", pvValeur: 43,
    photo: "https://images.unsplash.com/photo-1559589689-577ded92465b?w=400&h=300&fit=crop&q=80",
    prixCHR: 4.20, prixMarchand: 4.50, prixParticulier: 5.00,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 5.00, marketplaceOrdre: 54,
    marketplaceDescription: "Thym frais parfumé pour les marinades, rôtis et tajines.",
    marketplaceTags: ["herbes", "thym", "aromatiques", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-041", nom: "Romarin Frais", nomAr: "إكليل الجبل", famille: "Herbes",
    unite: "botte", um: "Botte", colisageParUM: 1,
    stockDisponible: 50, stockDefect: 3, shelfLifeJours: 10, alerteShelfLifeJours: 2,
    prixAchat: 4.0, pvMethode: "pourcentage", pvValeur: 38,
    photo: "https://images.unsplash.com/photo-1564525632696-6e2d4aafc1e4?w=400&h=300&fit=crop&q=80",
    prixCHR: 4.80, prixMarchand: 5.00, prixParticulier: 5.52,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 6.00, marketplaceOrdre: 55,
    marketplaceDescription: "Romarin frais très parfumé, idéal pour les viandes grillées et les légumes rôtis.",
    marketplaceTags: ["herbes", "romarin", "aromatiques", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-042", nom: "Céleri Branche", nomAr: "كرفس", famille: "Herbes",
    unite: "pièce", um: "Botte", colisageParUM: 1,
    stockDisponible: 70, stockDefect: 5, shelfLifeJours: 10, alerteShelfLifeJours: 2,
    prixAchat: 3.0, pvMethode: "pourcentage", pvValeur: 33,
    photo: "https://images.unsplash.com/photo-1615485736407-5bcb4ea3cf40?w=400&h=300&fit=crop&q=80",
    prixCHR: 3.60, prixMarchand: 3.75, prixParticulier: 3.99,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 4.00, marketplaceOrdre: 56,
    marketplaceDescription: "Céleri en branches frais, croquant et parfumé pour soupes et sautés.",
    marketplaceTags: ["herbes", "céleri", "aromatiques", "frais"],
    actif: true, catalogueVisible: true,
  },
  {
    id: "seed-art-043", nom: "Fenouil", nomAr: "بسباس", famille: "Herbes",
    unite: "pièce", um: "Pièce", colisageParUM: 1,
    stockDisponible: 45, stockDefect: 3, shelfLifeJours: 10, alerteShelfLifeJours: 2,
    prixAchat: 5.0, pvMethode: "pourcentage", pvValeur: 40,
    photo: "https://images.unsplash.com/photo-1615485736407-5bcb4ea3cf40?w=400&h=300&fit=crop&q=80",
    prixCHR: 6.00, prixMarchand: 6.25, prixParticulier: 7.00,
    marketplaceActif: true, marketplaceStatut: "disponible",
    marketplacePrixPublic: 7.50, marketplaceOrdre: 57,
    marketplaceDescription: "Fenouil frais anisé, délicieux cru ou cuit. Très apprécié en cuisine méditerranéenne.",
    marketplaceTags: ["herbes", "fenouil", "aromatiques", "frais"],
    actif: true, catalogueVisible: true,
  },
]

// ── Fournisseurs ──────────────────────────────────────────────────────────────
export const SEED_FOURNISSEURS: Fournisseur[] = [
  {
    id: "seed-fo-001",
    nom: "Ferme Souss Agri",
    contact: "Mohammed Ait Benhaddou",
    telephone: "0661987654",
    email: "souss.agri@demo.ma",
    adresse: "Douar Oulad Said, Agadir",
    ville: "Agadir",
    region: "Souss-Massa",
    specialites: ["Tomates Rondes", "Avocats Hass", "Oranges Navel"],
    modalitePaiement: "virement",
    delaiPaiement: 30,
    ice: "001234567000045",
    itineraires: [
      { lat: 30.4278, lng: -9.5981, nom: "Marché de Gros Agadir" },
      { lat: 33.5912, lng: -7.6116, nom: "Marché de Gros Casablanca" },
    ],
  },
  {
    id: "seed-fo-002",
    nom: "Coopérative Meknès",
    contact: "Rachida Benali",
    telephone: "0535445566",
    email: "coop.meknes@demo.ma",
    adresse: "Route d'Azrou, Meknès",
    ville: "Meknès",
    region: "Fès-Meknès",
    specialites: ["Pommes de Terre", "Carottes", "Oignons"],
    modalitePaiement: "cheque",
    delaiPaiement: 15,
    itineraires: [
      { lat: 33.8935, lng: -5.5473, nom: "Marché Meknès" },
    ],
  },
  {
    id: "seed-fo-003",
    nom: "Coopérative Gharb",
    contact: "Khalid Zemmouri",
    telephone: "0537789012",
    email: "gharb.coop@demo.ma",
    adresse: "Sidi Slimane, Gharb",
    ville: "Sidi Slimane",
    region: "Rabat-Salé-Kénitra",
    specialites: ["Fraises Kenitra", "Clémentines", "Poivrons"],
    modalitePaiement: "cash",
    delaiPaiement: 7,
    itineraires: [
      { lat: 34.2667, lng: -5.9317, nom: "Marché Sidi Slimane" },
    ],
  },
]

// ── Livreurs ─────────────────────────────────────────────────────────────────
export const SEED_LIVREURS: Livreur[] = [
  {
    id: "seed-lv-001",
    type: "interne",
    nom: "Benhaddou",
    prenom: "Youssef",
    telephone: "0661112233",
    cin: "AB123456",
    typeVehicule: "camion",
    marqueVehicule: "Mercedes Atego",
    matricule: "A-12345-B",
    capaciteCaisses: 200,
    capaciteTonnage: 5000,
    actif: true,
  },
  {
    id: "seed-lv-002",
    type: "interne",
    nom: "Oukili",
    prenom: "Hamza",
    telephone: "0662223344",
    cin: "CD789012",
    typeVehicule: "camionnette",
    marqueVehicule: "Renault Master",
    matricule: "B-67890-C",
    capaciteCaisses: 80,
    capaciteTonnage: 1500,
    actif: true,
  },
]

// ── Commandes ─────────────────────────────────────────────────────────────────
export const SEED_COMMANDES: Commande[] = [
  {
    id: "seed-cmd-001",
    date: daysAgo(5),
    commercialId: "seed",
    commercialNom: "Admin Demo",
    clientId: "seed-cl-001",
    clientNom: "Épicerie Al Amal",
    secteur: "Hay Hassani",
    zone: "Casablanca Sud",
    gpsLat: 33.536, gpsLng: -7.655,
    heurelivraison: "08:00",
    statut: "livre",
    emailDestinataire: "alaimal@demo.ma",
    lignes: [
      { articleId: "seed-art-001", articleNom: "Tomates Rondes", unite: "kg", quantite: 30, prixUnitaire: 4.32, prixVente: 4.32, total: 129.6 },
      { articleId: "seed-art-006", articleNom: "Carottes", unite: "kg", quantite: 20, prixUnitaire: 2.34, prixVente: 2.34, total: 46.8 },
    ],
  },
  {
    id: "seed-cmd-002",
    date: daysAgo(3),
    commercialId: "seed",
    commercialNom: "Admin Demo",
    clientId: "seed-cl-002",
    clientNom: "Superette Nour",
    secteur: "Ain Chock",
    zone: "Casablanca Est",
    gpsLat: 33.553, gpsLng: -7.543,
    heurelivraison: "09:30",
    statut: "valide",
    emailDestinataire: "nour.superette@demo.ma",
    lignes: [
      { articleId: "seed-art-003", articleNom: "Fraises Kenitra", unite: "kg", quantite: 10, prixUnitaire: 25.2, prixVente: 25.2, total: 252 },
      { articleId: "seed-art-005", articleNom: "Avocats Hass", unite: "kg", quantite: 15, prixUnitaire: 30.36, prixVente: 30.36, total: 455.4 },
    ],
  },
  {
    id: "seed-cmd-003",
    date: daysAgo(1),
    commercialId: "seed",
    commercialNom: "Admin Demo",
    clientId: "seed-cl-003",
    clientNom: "Marché Centrale Wholesale",
    secteur: "Derb Omar",
    zone: "Casablanca Centre",
    gpsLat: 33.591, gpsLng: -7.617,
    heurelivraison: "06:00",
    statut: "en_attente",
    emailDestinataire: "centrale.wholesale@demo.ma",
    lignes: [
      { articleId: "seed-art-002", articleNom: "Pommes de Terre", unite: "kg", quantite: 500, prixUnitaire: 2.73, prixVente: 2.73, total: 1365 },
      { articleId: "seed-art-004", articleNom: "Oranges Navel", unite: "kg", quantite: 200, prixUnitaire: 5.625, prixVente: 5.625, total: 1125 },
      { articleId: "seed-art-007", articleNom: "Citrons Eureka", unite: "kg", quantite: 100, prixUnitaire: 6.4, prixVente: 6.4, total: 640 },
    ],
  },
  {
    id: "seed-cmd-004",
    date: daysAgo(2),
    commercialId: "seed",
    commercialNom: "Admin Demo",
    clientId: "seed-cl-004",
    clientNom: "Restaurant Le Patio",
    secteur: "Anfa",
    zone: "Casablanca Ouest",
    gpsLat: 33.587, gpsLng: -7.668,
    heurelivraison: "07:00",
    statut: "en_transit",
    emailDestinataire: "contact@lepatio-demo.ma",
    lignes: [
      { articleId: "seed-art-001", articleNom: "Tomates Rondes", unite: "kg", quantite: 25, prixUnitaire: 4.32, prixVente: 4.32, total: 108 },
      { articleId: "seed-art-003", articleNom: "Fraises Kenitra", unite: "kg", quantite: 5, prixUnitaire: 25.2, prixVente: 25.2, total: 126 },
      { articleId: "seed-art-008", articleNom: "Bananes Cavendish", unite: "kg", quantite: 30, prixUnitaire: 9.9, prixVente: 9.9, total: 297 },
    ],
  },
  {
    id: "seed-cmd-005",
    date: daysAgo(7),
    commercialId: "seed",
    commercialNom: "Admin Demo",
    clientId: "seed-cl-006",
    clientNom: "Hôtel Mogador Essaouira",
    secteur: "Essaouira",
    zone: "Région Marrakech-Safi",
    gpsLat: 31.508, gpsLng: -9.760,
    heurelivraison: "10:00",
    statut: "livre",
    emailDestinataire: "approvisionnement@mogador-demo.ma",
    lignes: [
      { articleId: "seed-art-004", articleNom: "Oranges Navel", unite: "kg", quantite: 80, prixUnitaire: 5.625, prixVente: 5.625, total: 450 },
      { articleId: "seed-art-005", articleNom: "Avocats Hass", unite: "kg", quantite: 40, prixUnitaire: 30.36, prixVente: 30.36, total: 1214.4 },
      { articleId: "seed-art-008", articleNom: "Bananes Cavendish", unite: "kg", quantite: 60, prixUnitaire: 9.9, prixVente: 9.9, total: 594 },
    ],
  },
]

// ── Bons de Livraison ─────────────────────────────────────────────────────────
export const SEED_BONS_LIVRAISON: BonLivraison[] = [
  {
    id: "seed-bl-001",
    date: daysAgo(5),
    tripId: "seed-tr-001",
    commandeId: "seed-cmd-001",
    clientNom: "Épicerie Al Amal",
    secteur: "Hay Hassani",
    zone: "Casablanca Sud",
    livreurNom: "Youssef Benhaddou",
    prevendeurNom: "Admin Demo",
    lignes: [
      { articleNom: "Tomates Rondes", unite: "kg", quantite: 30, prixUnitaire: 4.32, total: 129.6 },
      { articleNom: "Carottes", unite: "kg", quantite: 20, prixUnitaire: 2.34, total: 46.8 },
    ],
    montantTotal: 176.4,
    tva: 0,
    montantTTC: 176.4,
    statut: "encaissé",
    statutLivraison: "livre",
    heureLivraisonReelle: "08:15",
    nbCaisseGros: 2,
    nbCaisseDemi: 2,
  },
  {
    id: "seed-bl-002",
    date: daysAgo(7),
    tripId: "seed-tr-002",
    commandeId: "seed-cmd-005",
    clientNom: "Hôtel Mogador Essaouira",
    secteur: "Essaouira",
    zone: "Région Marrakech-Safi",
    livreurNom: "Hamza Oukili",
    prevendeurNom: "Admin Demo",
    lignes: [
      { articleNom: "Oranges Navel", unite: "kg", quantite: 80, prixUnitaire: 5.625, total: 450 },
      { articleNom: "Avocats Hass", unite: "kg", quantite: 40, prixUnitaire: 30.36, total: 1214.4 },
      { articleNom: "Bananes Cavendish", unite: "kg", quantite: 60, prixUnitaire: 9.9, total: 594 },
    ],
    montantTotal: 2258.4,
    tva: 451.68,
    montantTTC: 2710.08,
    statut: "encaissé",
    statutLivraison: "livre",
    heureLivraisonReelle: "11:30",
    nbCaisseGros: 10,
    nbCaisseDemi: 4,
  },
]

// ── Purchase Orders ───────────────────────────────────────────────────────────
export const SEED_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "seed-po-001",
    date: daysAgo(4),
    articleId: "seed-art-001",
    articleNom: "Tomates Rondes",
    articleUnite: "kg",
    fournisseurId: "seed-fo-001",
    fournisseurNom: "Ferme Souss Agri",
    fournisseurEmail: "souss.agri@demo.ma",
    quantite: 400,
    prixUnitaire: 3.2,
    total: 1280,
    statut: "receptionné",
    notes: "Commande hebdomadaire — priorité qualité A",
    createdBy: "seed",
    montantPaye: 1280,
    statutPaiement: "solde",
    datePaiement: daysAgo(2),
    genereAuto: false,
  },
  {
    id: "seed-po-002",
    date: daysAgo(2),
    articleId: "seed-art-002",
    articleNom: "Pommes de Terre",
    articleUnite: "kg",
    fournisseurId: "seed-fo-002",
    fournisseurNom: "Coopérative Meknès",
    fournisseurEmail: "coop.meknes@demo.ma",
    quantite: 600,
    prixUnitaire: 2.1,
    total: 1260,
    statut: "envoyé",
    notes: "",
    createdBy: "seed",
    montantPaye: 0,
    statutPaiement: "impaye",
    genereAuto: true,
  },
  {
    id: "seed-po-003",
    date: daysAgo(1),
    articleId: "seed-art-003",
    articleNom: "Fraises Kenitra",
    articleUnite: "kg",
    fournisseurId: "seed-fo-003",
    fournisseurNom: "Coopérative Gharb",
    fournisseurEmail: "gharb.coop@demo.ma",
    quantite: 100,
    prixUnitaire: 18.0,
    total: 1800,
    statut: "ouvert",
    notes: "Fraises calibre 30+ uniquement",
    createdBy: "seed",
    montantPaye: 0,
    statutPaiement: "impaye",
    genereAuto: false,
  },
]

// ── Réceptions ────────────────────────────────────────────────────────────────
export const SEED_RECEPTIONS: Reception[] = [
  {
    id: "seed-re-001",
    date: daysAgo(4),
    bonAchatId: "",
    purchaseOrderId: "seed-po-001",
    fournisseurNom: "Ferme Souss Agri",
    source: "purchase_order",
    lignes: [
      {
        articleId: "seed-art-001",
        articleNom: "Tomates Rondes",
        quantiteCommandee: 400,
        quantiteRecue: 395,
        quantiteFacturee: 400,
        prixAchat: 3.2,
        prixFacture: 3.2,
        ecartQte: -5,
        ecartPrix: 0,
        motifReliquat: "5 kg abîmés refusés à la réception",
      },
    ],
    statut: "validée",
    operateurId: "seed",
    notes: "Réception conforme — manque 5 kg qualité insuffisante",
  },
]

// ── Trips ─────────────────────────────────────────────────────────────────────
export const SEED_TRIPS: Trip[] = [
  {
    id: "seed-tr-001",
    numero: "T001",
    date: daysAgo(5),
    livreurId: "seed-lv-001",
    livreurNom: "Youssef Benhaddou",
    vehicule: "Mercedes Atego — A-12345-B",
    commandeIds: ["seed-cmd-001"],
    statut: "terminé",
    itineraire: [
      { lat: 33.536, lng: -7.655, clientNom: "Épicerie Al Amal", ordre: 1 },
    ],
    kmDepart: 12450,
    kmArrivee: 12498,
    kmTotal: 48,
    kmDepartConfirme: true,
    caissesValidees: true,
  },
  {
    id: "seed-tr-002",
    numero: "T002",
    date: daysAgo(7),
    livreurId: "seed-lv-002",
    livreurNom: "Hamza Oukili",
    vehicule: "Renault Master — B-67890-C",
    commandeIds: ["seed-cmd-005"],
    statut: "terminé",
    itineraire: [
      { lat: 31.508, lng: -9.760, clientNom: "Hôtel Mogador Essaouira", ordre: 1 },
    ],
    kmDepart: 34200,
    kmArrivee: 34562,
    kmTotal: 362,
    kmDepartConfirme: true,
    caissesValidees: true,
  },
  {
    id: "seed-tr-003",
    numero: "T003",
    date: daysAgo(2),
    livreurId: "seed-lv-001",
    livreurNom: "Youssef Benhaddou",
    vehicule: "Mercedes Atego — A-12345-B",
    commandeIds: ["seed-cmd-004"],
    statut: "en_cours",
    itineraire: [
      { lat: 33.587, lng: -7.668, clientNom: "Restaurant Le Patio", ordre: 1 },
    ],
    kmDepart: 12498,
    kmDepartConfirme: true,
    caissesValidees: false,
  },
]

// ── Seed function ─────────────────────────────────────────────────────────────
export function seedDemoData(storeRef: typeof import("./store").store) {
  function mergeById<T extends { id: string }>(existing: T[], seeds: T[]): T[] {
    const map = new Map(existing.map(x => [x.id, x]))
    seeds.forEach(s => { if (!map.has(s.id)) map.set(s.id, s) })
    return Array.from(map.values())
  }

  storeRef.saveClients(mergeById(storeRef.getClients(), SEED_CLIENTS))
  storeRef.saveArticles(mergeById(storeRef.getArticles(), SEED_ARTICLES))
  storeRef.saveFournisseurs(mergeById(storeRef.getFournisseurs(), SEED_FOURNISSEURS))
  storeRef.saveCommandes(mergeById(storeRef.getCommandes(), SEED_COMMANDES))
  storeRef.saveBonsLivraison(mergeById(storeRef.getBonsLivraison(), SEED_BONS_LIVRAISON))
  storeRef.savePurchaseOrders(mergeById(storeRef.getPurchaseOrders(), SEED_PURCHASE_ORDERS))
  storeRef.saveReceptions(mergeById(storeRef.getReceptions(), SEED_RECEPTIONS))
  storeRef.saveTrips(mergeById(storeRef.getTrips(), SEED_TRIPS))

  const existing: Livreur[] = (() => {
    try { return JSON.parse(localStorage.getItem("fl_livreurs") ?? "[]") } catch { return [] }
  })()
  localStorage.setItem("fl_livreurs", JSON.stringify(mergeById(existing, SEED_LIVREURS)))
}
